version: '3'

services:
  node:
    image: node:9
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "cd /app && node index.js"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql
    volumes:
      - .docker/db:/var/lib/mysql
    ports:
      - "3035:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 123#pass
      MYSQL_DATABASE: test